apiVersion: v1
kind: Service
metadata:
  name: {{ include "associate-stack.id" . }}-frontend
  labels:
    {{- include "associate-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ include "associate-stack.id" . | quote }}
  ports:
    - name: http
      port: 4200
      targetPort: http