// GENERATED by scripts/sync-config.mjs from Application/Config/application.yml and
// Application/.env. Do not edit: change Config or .env, then run npm start / build / test.
//
// The addresses below are the build-time defaults. When the page is served by the
// Docker image, /app-config.js (loaded by index.html) sets window.__APP_CONFIG__ at
// container start and its values win; an empty string means "the same address as
// the page", which is what one load balancer, an Ingress or CloudFront needs.
const runtime: { tradeApiUrl?: string; authApiUrl?: string } =
  (globalThis as { __APP_CONFIG__?: { tradeApiUrl?: string; authApiUrl?: string } }).__APP_CONFIG__ ?? {};
const pick = (value: string | undefined, fallback: string): string =>
  (typeof value === 'string' ? value : fallback).replace(/\/+$/, '');
const tradeApiUrl = pick(runtime.tradeApiUrl, 'http://localhost:8081');
const authApiUrl = pick(runtime.authApiUrl, 'http://localhost:3000');
/** The origin a URL points at; a relative or empty URL is the page's own origin. */
const originOf = (url: string): string => new URL(url || '/', globalThis.location?.origin).origin;

export const environment = {
  production: true,
  tradeApiUrl,
  authApiUrl,
  /**
   * The only origins the interceptor will send a bearer token to. Derived from the
   * two API URLs so the allow list cannot drift from where requests actually go.
   */
  platformOrigins: [originOf(tradeApiUrl), originOf(authApiUrl)],
};
