apiVersion: v1
kind: Namespace
metadata:
  name: team-01
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-02
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-03
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-04
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-05
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-06
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-07
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-08
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-09
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-10
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-11
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-12
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-13
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-14
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-15
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-16
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-17
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-18
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-19
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-20
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-21
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-22
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-23
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-24
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-25
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-26
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-27
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-28
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-29
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-30