apiVersion: v1
kind: Service
metadata:
  name: {{ include "associate-stack.id" . }}-auth-service
  labels:
    {{- include "associate-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: auth-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: auth-service
    app.kubernetes.io/instance: {{ include "associate-stack.id" . | quote }}
  ports:
    - name: http
      port: 3000
      targetPort: http