// Writes src/environments/environment.ts and environment.prod.ts from the platform's
// configuration, so no service address is ever typed into the frontend's source.
//
// Where the values come from, first match wins:
//   1. environment variables      AUTH_SERVICE_URL, ORDER_SERVICE_URL (full URLs, port included)
//                                 e.g. Docker build args, or a CI job
//   2. Application/.env           the same keys
//   3. Application/Config/application.yml
//                                 services.auth.url + services.auth.port,
//                                 services.order.url + services.order.port
//
// Runs before `npm start`, `npm run build` and `npm test` (package.json pre-scripts),
// and in the Docker build. A browser bundle cannot read a file at run time, so the
// addresses are fixed at build time: rebuild after changing Config or .env.
//
//   node scripts/sync-config.mjs            write both files
//   node scripts/sync-config.mjs --print    also print what was used

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const frontend = join(dirname(fileURLToPath(import.meta.url)), '..');
const application = join(frontend, '..');

/** Flattens the plain `key: value` YAML of Config/application.yml into dotted keys. */
export function parseSharedConfig(text) {
  const out = {};
  const stack = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.replace(/\s+#.*$/, '');
    if (!line.trim() || line.trim().startsWith('#')) continue;
    const m = line.match(/^(\s*)([A-Za-z0-9_.-]+):\s*(.*)$/);
    if (!m) continue;
    const indent = m[1].length;
    while (stack.length && stack[stack.length - 1].indent >= indent) stack.pop();
    const key = [...stack.map((s) => s.key), m[2]].join('.');
    const value = m[3].trim().replace(/^["']|["']$/g, '');
    if (value) out[key] = value;
    else stack.push({ indent, key: m[2] });
  }
  return out;
}

/** KEY=value lines of a .env file (quotes removed); comments and blanks skipped. */
export function parseDotEnv(text) {
  const out = {};
  for (const raw of text.split(/\r?\n/)) {
    const m = raw.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*)\s*$/);
    if (m) out[m[1]] = m[2].replace(/^["']|["']$/g, '');
  }
  return out;
}

function read(path) {
  return existsSync(path) ? readFileSync(path, 'utf8') : '';
}

export function resolveUrls(env = process.env) {
  const dotEnv = parseDotEnv(read(join(application, '.env')));
  const shared = parseSharedConfig(read(env.SHARED_CONFIG || join(application, 'Config', 'application.yml')));
  const pick = (envKey, service) => {
    const fromEnv = env[envKey] || dotEnv[envKey];
    if (fromEnv) return { url: fromEnv.replace(/\/+$/, ''), source: env[envKey] ? 'environment' : '.env' };
    const host = shared[`services.${service}.url`];
    const port = shared[`services.${service}.port`];
    if (host && port) return { url: `${host.replace(/\/+$/, '')}:${port}`, source: 'Config/application.yml' };
    throw new Error(
      `${envKey} is not set and Config/application.yml has no services.${service}.url/port. ` +
        'Set one of them (see Application/.env.example).',
    );
  };
  return { auth: pick('AUTH_SERVICE_URL', 'auth'), order: pick('ORDER_SERVICE_URL', 'order') };
}

function environmentFile(production, tradeApiUrl, authApiUrl) {
  return `// GENERATED by scripts/sync-config.mjs from Application/Config/application.yml and
// Application/.env. Do not edit: change Config or .env, then run npm start / build / test.
//
// The addresses below are the build-time defaults. When the page is served by the
// Docker image, /app-config.js (loaded by index.html) sets window.__APP_CONFIG__ at
// container start and its values win; an empty string means "the same address as
// the page", which is what one load balancer, an Ingress or CloudFront needs.
const runtime: { tradeApiUrl?: string; authApiUrl?: string } =
  (globalThis as { __APP_CONFIG__?: { tradeApiUrl?: string; authApiUrl?: string } }).__APP_CONFIG__ ?? {};
const pick = (value: string | undefined, fallback: string): string =>
  (typeof value === 'string' ? value : fallback).replace(/\\/+$/, '');
const tradeApiUrl = pick(runtime.tradeApiUrl, '${tradeApiUrl}');
const authApiUrl = pick(runtime.authApiUrl, '${authApiUrl}');
/** The origin a URL points at; a relative or empty URL is the page's own origin. */
const originOf = (url: string): string => new URL(url || '/', globalThis.location?.origin).origin;

export const environment = {
  production: ${production},
  tradeApiUrl,
  authApiUrl,
  /**
   * The only origins the interceptor will send a bearer token to. Derived from the
   * two API URLs so the allow list cannot drift from where requests actually go.
   */
  platformOrigins: [originOf(tradeApiUrl), originOf(authApiUrl)],
};
`;
}

const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain) {
  const { auth, order } = resolveUrls();
  for (const url of [auth.url, order.url]) new URL(url); // fail fast on a malformed address
  const dir = join(frontend, 'src', 'environments');
  writeFileSync(join(dir, 'environment.ts'), environmentFile(false, order.url, auth.url));
  writeFileSync(join(dir, 'environment.prod.ts'), environmentFile(true, order.url, auth.url));
  if (process.argv.includes('--print')) {
    console.log(`order API ${order.url} (from ${order.source})`);
    console.log(`auth API  ${auth.url} (from ${auth.source})`);
  }
}
