apiVersion: v1
kind: Service
metadata:
  name: {{ include "associate-stack.id" . }}-kafka
  labels:
    {{- include "associate-stack.labels" . | nindent 4 }}
    app.kubernetes.io/name: kafka
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/instance: {{ include "associate-stack.id" . | quote }}
  ports:
    - name: kafka
      port: 29092
      targetPort: kafka
    - name: controller
      port: 9093
      targetPort: controller