apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: trading-platform-tester
  region: us-east-1
managedNodeGroups:
  - name: tester-workers
    instanceType: t3.medium
    minSize: 1
    desiredCapacity: 1
    maxSize: 2
    volumeSize: 30
    privateNetworking: true
iam:
  withOIDC: true
addons:
  - name: vpc-cni
  - name: kube-proxy
  - name: coredns
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true