apiVersion: v1
kind: Service
metadata:
  name: trade-executor
  namespace: tester
spec:
  type: ClusterIP
  selector:
    app: trade-executor
  ports:
    - name: http
      port: 8083
      targetPort: http